### ISSUE TITLE
EE: Update visualiser for new layers

### ISSUE THREAD

**Issue by biggsbenjamin** [AlexMontgomerie/fpgaconvnet-optimiser#54]
# Layers:

- [x] `BufferLayer`
- [x] `SplitLayer`
- [x] `ExitConditionLayer`
- [x] `ExitSelectionLayer`

## Additional files to fix:

- [x] Network.py
- [x] Partition.py
- [x] matrix.py

### Tasks:
- [x] vis for full network
- [x] vis for subgraph partitions (not ONNX subgraphs)
- [x] Make the cluster naming for the partitions more useful
- [x] Add ctrl edges
- [x] Get rid of the random squeeze layer added on the end of the EC
